config_path = "../docs/config.json"

decorative_blocks = [
    'andesite', 'blackstone', 'blue_ice', 'bone_block', 'brick_block',
    'chiseled_quartz_block', 'chiseled_red_sandstone', 'chiseled_sandstone', 'chiseled_stone_bricks',
    'clay', 'coal_block', 'cobblestone', 'cracked_stone_bricks', 'mossy_stone_bricks', 'cut_red_sandstone', 'cut_sandstone',
    'diamond_block', 'diorite', 'end_stone_bricks', 'glowstone', 'gold_block', 'granite',
    'honeycomb_block', 'iron_block', 'lapis_block', 'polished_andesite', 'polished_blackstone', 'polished_diorite',
    'polished_granite', 'prismarine', 'prismarine_bricks', 'purpur_block', 'quartz_block', 'quartz_pillar',
    'red_sandstone',  'sandstone', 'smooth_quartz', 'smooth_red_sandstone',
    'smooth_sandstone', 'smooth_stone', 'snow_block', 'stone', 'stone_bricks',
    'terracotta', 'warped_stem', 'glass', 'magma_block', 'red_nether_bricks', 'chiseled_nether_bricks',
    'oak_planks', 'spruce_planks', 'birch_planks', 'jungle_planks', 'acacia_planks', 'dark_oak_planks',
    'oak_log', 'spruce_log', 'birch_log', 'jungle_log', 'acacia_log', 'dark_oak_log', 
    'oak_wood', 'spruce_wood', 'birch_wood', 'jungle_wood', 'acacia_wood', 'dark_oak_wood', 
    'white_stained_glass', 'orange_stained_glass', 'magenta_stained_glass',
    'light_blue_stained_glass', 'yellow_stained_glass', 'lime_stained_glass',
    'pink_stained_glass', 'gray_stained_glass', 'light_gray_stained_glass', 'cyan_stained_glass', 'purple_stained_glass',
    'blue_stained_glass', 'brown_stained_glass', 'green_stained_glass', 'red_stained_glass', 'black_stained_glass',
    'white_concrete', 'orange_concrete', 'magenta_concrete',
    'light_blue_concrete', 'yellow_concrete', 'lime_concrete',
    'pink_concrete', 'gray_concrete', 'light_gray_concrete', 'cyan_concrete', 'purple_concrete',
    'blue_concrete', 'brown_concrete', 'green_concrete', 'red_concrete', 'black_concrete',
    'white_glazed_terracotta', 'orange_glazed_terracotta', 'magenta_glazed_terracotta',
    'light_blue_glazed_terracotta', 'yellow_glazed_terracotta', 'lime_glazed_terracotta',
    'pink_glazed_terracotta', 'gray_glazed_terracotta', 'light_gray_glazed_terracotta', 'cyan_glazed_terracotta', 'purple_glazed_terracotta',
    'blue_glazed_terracotta', 'brown_glazed_terracotta', 'green_glazed_terracotta', 'red_glazed_terracotta', 'black_glazed_terracotta',
    'white_terracotta', 'orange_terracotta', 'magenta_terracotta',
    'light_blue_terracotta', 'yellow_terracotta', 'lime_terracotta',
    'pink_terracotta', 'gray_terracotta', 'light_gray_terracotta', 'cyan_terracotta', 'purple_terracotta',
    'blue_terracotta', 'brown_terracotta', 'green_terracotta', 'red_terracotta', 'black_terracotta',
    'wool', 'orange_wool', 'magenta_wool',
    'light_blue_wool', 'yellow_wool', 'lime_wool',
    'pink_wool', 'gray_wool', 'light_gray_wool', 'cyan_wool', 'purple_wool',
    'blue_wool', 'brown_wool', 'green_wool', 'red_wool', 'black_wool'
]

#decorative_blocks = ["andesite",    "bedrock",    "blackstone",    "blackstone_bricks",    "brick",    "chiseled_nether_bricks",    "chiseled_polished_blackstone",    "cobblestone",    "cracked_nether_bricks",    "cracked_polished_blackstone_bricks",    "cut_red_sandstone",    "cut_sandstone",    "diorite",    "end_stone_bricks",    "gilded_blackstone",    "glowstone",    "granite",    "gravel",    "infested_chiseled_stone_bricks",    "infested_cobblestone",    "infested_cracked_stone_bricks",    "infested_mossy_stone_bricks",    "infested_stone",    "infested_stone_bricks",    "mossy_cobblestone",    "mossy_stone_bricks",    "nether_bricks",    "nether_gold_ore",    "nether_quartz_ore",    "obsidian",    "polished_andesite",    "polished_blackstone",    "polished_blackstone_bricks",    "polished_diorite",    "polished_granite",    "red_nether_bricks",    "red_sandstone",    "sandstone",    "smooth_quartz",    "smooth_red_sandstone",    "smooth_sandstone",    "soul_sand",    "soul_soil",    "stone",    "stone_bricks",    "terracotta",    "white_wool",    "orange_wool",    "magenta_wool",    "light_blue_wool",    "yellow_wool",    "lime_wool",    "pink_wool",    "gray_wool",    "light_gray_wool",    "cyan_wool",    "purple_wool",    "blue_wool",    "brown_wool",    "green_wool",    "red_wool",    "black_wool",    "grass_block",    "mycelium",    "podzol"]
concrete_blocks = [  "black_concrete",    "blue_concrete",    "brown_concrete",    "cyan_concrete",    "gray_concrete",    "green_concrete",    "light_blue_concrete",    "lime_concrete",    "magenta_concrete",    "orange_concrete",    "pink_concrete",    "purple_concrete",    "red_concrete",    "white_concrete",    "yellow_concrete"]


block_colors = {(143, 61, 46), (224, 97, 0), (57, 42, 35), (218, 224, 162), (186, 99, 29), (42, 35, 40), (76, 83, 42),
                (188, 188, 188), (169, 48, 159), (216, 202, 155), (152, 94, 67), (99, 171, 158), (119, 118, 119),
                (30, 67, 140), (216, 215, 210), (233, 236, 236), (192, 193, 194), (99, 156, 151), (216, 203, 155),
                (58, 175, 217), (73, 91, 36), (127, 127, 127), (94, 168, 24), (16, 15, 15), (58, 58, 77),
                (142, 142, 134), (229, 148, 29), (112, 185, 25), (189, 101, 31), (171, 131, 84), (169, 125, 169),
                (217, 206, 159), (84, 109, 27), (62, 68, 71), (158, 158, 158), (149, 103, 85), (85, 67, 25),
                (122, 121, 122), (246, 208, 61), (125, 125, 125), (132, 134, 133), (0, 0, 3), (209, 178, 161),
                (171, 132, 84), (109, 85, 50), (96, 76, 49), (35, 137, 198), (213, 101, 142), (207, 213, 214),
                (125, 125, 115), (196, 176, 118), (231, 226, 218), (160, 166, 179), (177, 144, 86), (53, 48, 56),
                (118, 117, 118), (240, 175, 21), (15, 10, 24), (161, 83, 37), (103, 96, 86), (161, 78, 78),
                (186, 133, 35), (174, 92, 59), (154, 106, 89), (183, 96, 27), (115, 89, 52), (58, 37, 16), (60, 46, 26),
                (142, 32, 32), (116, 167, 253), (189, 68, 179), (136, 136, 136), (220, 220, 220), (98, 237, 228),
                (54, 57, 61)}

chain_blocks = {"0" : "white_wool",
                "1" : "red_wool",
                "2" : "blue_wool",
                "3" : "yellow_wool",
                "4" : "lime_wool",
                "5" : "pink_wool",
                "6" : "light_gray_wool",
                "7" : "purple_wool",
                "8" : "light_blue_wool",
                "9" : "green_wool",
                "10": "orange_wool"}

dark_skeleton_blocks = {"0b": "white_terracotta",
                        "1b": "red_terracotta",
                        "2b": "blue_terracotta",
                        "3b": "yellow_terracotta",
                        "4b": "lime_terracotta",
                        "5b": "pink_terracotta",
                        "6b": "light_gray_terracotta",
                        "7b": "purple_terracotta",
                        "8b": "light_blue_terracotta",
                        "9b": "green_terracotta",
                        "10b": "orange_terracotta"}

radii = {"C": 1.0,
         "N": 0.9285,
         "O": 0.857,
         "S": 1.428,
         "P": 1.428,
         "Mg": 2.142,
         "K": 3.1428,
         "Ca": 2.5714}

hydrophobic = {"R": "emerald_block",
               "K": "weathered_copper",
               "D": "cobblestone",
               "E": "light_gray_wool",
               "N": "end_stone",
               "Q": "end_stone_bricks",
               "H": "white_glazed_terracotta",
               "P": "verdant_froglight",
               "Y": "white_wool",
               "W": "snow",
               "S": "snow",
               "T": "snow",
               "G": "snow",
               "A": "pearlescent_froglight",
               "M": "ochre_froglight",
               "C": "cherry_leaves",
               "F": "cherry_planks",
               "L": "pink_wool",
               "V": "pink_concrete",
               "I": "red_mushroom_block"}

group = {"R": "red_wool",
         "H": "red_wool",
         "K": "red_wool",
         "D": "blue_wool",
         "E": "blue_wool",
         "S": "yellow_wool",
         "T": "yellow_wool",
         "N": "yellow_wool",
         "Q": "yellow_wool",
         "C": "orange_wool",
         "G": "orange_wool",
         "P": "orange_wool",
         "A": "green_wool",
         "I": "green_wool",
         "L": "green_wool",
         "M": "green_wool",
         "F": "green_wool",
         "W": "green_wool",
         "Y": "green_wool",
         "V": "green_wool"}

charge = {"R": "emerald_block",
               "K": "weathered_copper",
               "D": "cobblestone",
               "E": "light_gray_wool",
               "N": "end_stone",
               "Q": "end_stone_bricks",
               "H": "white_glazed_terracotta",
               "P": "verdant_froglight",
               "Y": "white_wool",
               "W": "snow",
               "S": "snow",
               "T": "snow",
               "G": "snow",
               "A": "pearlescent_froglight",
               "M": "ochre_froglight",
               "C": "cherry_leaves",
               "F": "cherry_planks",
               "L": "pink_wool",
               "V": "pink_concrete",
               "I": "red_mushroom_block"}
